---
- name: Include Windows Tasks
  ansible.builtin.include_tasks: windows.yml
  when: ansible_os_family == 'Windows'

- name: Include Linux Tasks
  ansible.builtin.include_tasks: linux.yml
  when: ansible_os_family != 'Windows'
